PRAGMA foreign_keys = ON;
PRAGMA auto_vacuum = FULL;

CREATE TABLE LAYER (
  LAYER_ID	       	INTEGER PRIMARY KEY,
  NAME  	 	VARCHAR NOT NULL		
);

CREATE TABLE CATEGORY (
  CATEGORY_ID	       	INTEGER PRIMARY KEY,
  LAYER_ID		INTEGER NOT NULL,
  NAME  	 	VARCHAR NOT NULL,
  IMAGE_PATH		VARCHAR NOT NULL,				
  IS_ACTIVE		BOOLEAN NOT NULL
);

CREATE TABLE MAP_OBJECT (
  OBJECT_ID	       	INTEGER PRIMARY KEY,
  CATEGORY_ID		INTEGER NOT NULL,
  NAME  	 	VARCHAR NOT NULL,
  IMAGE_PATH		VARCHAR NOT NULL				
);

